### ISSUE TITLE
Wrong scale and wrong drawing

### ISSUE THREAD

**Issue by Avatarchik** [UnityTech/UIWidgets#150]
Hi! Wrong scale and wrong drawing, I repeated the example https://www.youtube.com/watch?v=5KbiU-93-yU , but the display is not correct, everything is small, the buttons have a rounding wrong, the picture in the favorite item is also not correct drawn

Bug Video: https://monosnap.com/file/H87LBr2xudui0tKENfmtHhFsI1rBR9

Unity 2019.1
Unity Project: https://drive.google.com/open?id=1yUTlIVfLpGKG4QceutsUeTx-4SNWp39W
Flutter Project: https://github.com/devefy/Flutter-Story-App-UI

**Comment by kgdev** [comment]
Thanks for your reporting.

In the editor mode, the DPI is from your current screen instead of your game view by default. If you select a device of a different DPI, you can override the setting in the inspector of the game object.
![image](https://user-images.githubusercontent.com/6348456/56858066-2869fb80-69a7-11e9-9b0e-56c062285513.png)

For the round corners, we will have a check and get back to you soon.

**Comment by kgdev** [comment]
But when running in the device, you don't need to override this setting.

**Comment by Avatarchik** [comment]
Thank! This card is not drawn as in the demo
https://monosnap.com/file/tdpTQNpDzxiafEJ2cb2Zx9sqLJG2kS

**Comment by kgdev** [comment]
Please make sure the "Non Power of 2" is disabled for the images.
![image](https://user-images.githubusercontent.com/6348456/56877961-38a3d880-6a84-11e9-9380-7763fb9b9666.png)

**Comment by kgdev** [comment]
https://github.com/UnityTech/UIWidgets/pull/158
