### ISSUE TITLE
UIElements vs UIWidgets

### ISSUE THREAD

**Issue by kenofori** [UnityTech/UIWidgets#211]
Hi there

Whats the vision behind UIWidgets when Unity is already working on UI Elements and Runtime support?

Thanks

**Comment by kgdev** [comment]
UIWidgets is a port from Flutter. So most of the Flutter features can be leveraged directly in Unity by using UIWidgets. Standing on the shoulders of giants, we can have the modern way (componentized and functional) to build Apps/editor UI in Unity, instead of an old imperative way.

**Comment by kenofori** [comment]
So how Unity is going to support it? Will we see it actively developed? Why there is no blog post about it?
Can we rely on it for years to come Because Flutter itself will be continually developed.

Im asking this because Unity few years ago built a List View Framework but then abandoned it.

**Comment by jdnichollsc** [comment]
@kenofori but this is a new project, right?

**Comment by kgdev** [comment]
Thanks. UIWidgets would be a community driven project. Contributions are always welcome. And the core dev team is also actively developing this library.

**Comment by benoit-dupuis** [comment]
> So how Unity is going to support it? Will we see it actively developed? Why there is no blog post about it?
> Can we rely on it for years to come Because Flutter itself will be continually developed.
> 
> Im asking this because Unity few years ago built a List View Framework but then abandoned it.

This project is an experiment that is in no way officially supported by Unity. UIElements is the UI solution that we're committed to deliver to the users in order to build user interface for both the editor and the player, by providing a performant framework that is compatible with existing Unity features, and a set of tools to create and debug UI efficiently.

**Comment by jdnichollsc** [comment]
I have a stupid question, what defines the success of this project? I mean, to be officially supported by Unity 😅

**Comment by zhuxingwei** [comment]
UIWidgets is a community driven project which aim to explore more application scenarios of Unity by providing developers a novel and powerful UI framework to accomplish **ALL** kinds of goals, e.g., building games need fancy UI or building Apps with 3D models.

The dev team will continue to polish UIWidgets so that it can benefit from the upgrading of both flutter and the great Unity engine. The overall success of this project is made by all the bigger success of our users and their UIWidgets-based products.
